language: php
sudo: required
dist: trusty
os: linux
group: edge

php:
  - 7.0

env:
  - CC=gcc-4.8 CFLAGS=""
  - CC=clang   CFLAGS=""

before_install:
  - lsb_release -a
  - uname -a

before_script:
  - phpize
  - ./configure --enable-suhosin7-experimental --enable-suhosin7-debug
  - make -j2
  - phpenv config-rm xdebug.ini

script:
  - make test NO_INTERACTION=1
